stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  tags:
    - shared
  script:
    - cd express-api && docker compose build --no-cache && docker compose -p express-api up --remove-orphans --detach
