stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  tags:
    - shared
  script:
    - cd express-api && docker compose -p express-api down --remove-orphans
    - cd express-api && docker compose -p express-api build --no-cache
    - cd express-api && docker compose -p express-api up -d
