stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  tags:
    - shared
  script:
    - cd express-api && docker compose -p express-api down && docker compose -p express-api up --build --detach
