stages:
  - deploy

deploy-taltech:
  stage: deploy
  only:
    - main
  tags:
    - shared
  script:
    - cd vue-todo-express && docker compose -p vue-todo-express up --build --remove-orphans --detach
