stages:
  - deploy

deploy:
  stage: deploy
  only:
    - express
  tags:
    - shared
  script:
    - cd vue-todo && docker compose --env-file .env.express -p vue-todo-express up --build --remove-orphans --detach